kayitli-degil:
- 'Bu sunucuda kayıtlı değilsin lütfen www.arvalex.com dan kayıt ol!'
- ' '
gec-kaldin:
- 'Şifreyi uzun zaman boyunca giremediğin için atıldın!'
- 'Tekrar deneyebilirsin!'
sifre-yanlis:
- 'Bir çok defa şifreni yanlış girdin.'
- 'Şifreni unuttuysan www.arvalex.com'
title:
  title: '§a{0}'
  subtitle: '§7Saniye sonra lobiye aktarılacaksınız'
kick-result: 'KICK_WHITELIST'
lobi-komut: 'gitlanlobiye'
spawn-komut: 'spawn'
Giris:
  satir1: '§k'
  satir2: '§c^^^^^^^^'
  satir3: '§cGiriş Aşaması'
  satir4: '§4'
mysql:
  Host:
  User:
  Password:
  DB:
  Table: 'Accounts'